### ISSUE TITLE
Incorrect aggregated (1d) results

### ISSUE THREAD

**Issue by andrzej-r** [dbuezas/lovelace-plotly-graph-card#276] opened 2023-04-21 09:17 UTC
It is a rather elusive issue, I noticed it in the past but was having trouble reproducing it. I've now managed to capture screenshots of it today (taken at 9:01am, in case it matters).

Data averaged over a period of 1 hour show a periodic daily activity (as one would expect from a solar power generation plot). However, when I zoom out a bit more, to trigger averaging over 1 day periods, I get daily averages that do not match the former plot. Specifically, daily average on 14/4 is zero and first (partial) day on record 11/4 is significantly overestimated. Other days look broadly aligned with hourly averages and report from energy dashboard.

Hourly averages (statistic=mean stacked areas for "to grid", "to battery", "to house", statistic=max unstacked for "total max"):
![Screenshot_2023-04-21_09-01-59](https://user-images.githubusercontent.com/587630/233593246-a3a171dc-c403-4ccf-ae64-0f8493199a10.png)

The same but with daily averages:
![Screenshot_2023-04-21_09-01-30](https://user-images.githubusercontent.com/587630/233593283-57e5e4b5-788b-4f18-bc1a-8cafe5246330.png)

I have a feeling this may be triggered by moving boundaries of averaging periods. For example, now at 10:05am, the "zero" day has shifted to 12/4 - see below. Is there a way of forcing the aggregation to start at midnight, regardless of the current time? While this does not explain or fix the issue, it would likely be a sufficient work around for this plot.

![Screenshot_2023-04-21_10-08-19](https://user-images.githubusercontent.com/587630/233596010-548bcda2-8b42-4508-9d90-be8cc2d5078c.png)

Solar production plot from energy dashboard for reference:
![Screenshot_2023-04-21_10-14-16](https://user-images.githubusercontent.com/587630/233597812-40798aae-3d58-45cb-863a-657fa059628b.png)

**Comment by dbuezas** [comment] 2023-04-21 11:39
Hi Andrzej!
I agree with your suspicion that the HA API is not handling boundaries correctly.
Another user opened an issue in home assistant which is relevant to this: https://github.com/home-assistant/core/issues/88696#issuecomment-1444033948

I may try to work around it if this is not fixed in the upcoming months

**Comment by tomatensaus** [comment] 2023-05-02 07:32
With the latest update I also noticed that my graphs are disappearing. Recently upgraded to 
Home Assistant 2023.4.6 4 days ago and the graphs for the last 4 days are missing with the incorrect values being reported. Is there any way to work around the issue?

![image](https://user-images.githubusercontent.com/1019233/235606302-cc46fa14-cf3d-4079-a3c4-ed4eef280b3c.png)

**Comment by dbuezas** [comment] 2023-05-02 10:55
If you reload the page and the data is still missing, then you lost data from your database. Have you restored a backup?

Do the standard HA plot cards have this information?

**Comment by tomatensaus** [comment] 2023-05-02 11:08
No the data is all there, selecting hourly I can confirm that the values shown is not 0. I have not restored any DB. 

Initially I noticed strange values for yesterday but today looks good. After midnight (next day) the values that was good is suddenly now zero and today is good again. This pattern repeated itself for a couple of days and in the end it can only be a breaking change somewhere in Home Assistant/HA OS. Data before that still shows correctly
Added some console logs and I can see 0 values coming through
![image](https://user-images.githubusercontent.com/1019233/235650201-6d1133ce-a4f6-4f23-bead-b142021b29f1.png)

**Comment by dbuezas** [comment] 2023-05-02 11:23
Same if you remove your filters?

**Comment by tomatensaus** [comment] 2023-05-02 11:29
> Same if you remove your filters?

Same output... no filters
![image](https://user-images.githubusercontent.com/1019233/235653886-86cb3fa0-179e-4af7-a15e-6aad54011914.png)

period: day  simply returns 0 for all days since I upgraded... before that it still works

**Comment by dbuezas** [comment] 2023-05-02 11:33
Are you sure that the statistics card in HA shows different data? Note that "history" and "statistics" are two different tables

**Comment by tomatensaus** [comment] 2023-05-02 11:38
> Are you sure that the statistics card in HA shows different data? Note that "history" and "statistics" are two different tables

No I am not aware of this (quite new to home assistant, sorry). I showed the history in my last post and need to read up where I can find the statistics to view the values then. Sorry if I wasted your time

**Comment by dbuezas** [comment] 2023-05-02 11:48
Oh, no problem :).
Here's a standard Home Assistant card to see the statistics: https://www.home-assistant.io/dashboards/statistics-graph/

Let me know how it went!

**Comment by tomatensaus** [comment] 2023-05-02 11:56
Day
![image](https://user-images.githubusercontent.com/1019233/235659291-3133ee17-7e96-41e1-8806-9344574234b4.png)

Hour
![image](https://user-images.githubusercontent.com/1019233/235659477-45c4d357-f4ea-4bfd-b0db-68330256ba40.png)

**Comment by dbuezas** [comment] 2023-05-02 13:47
Yes, the long term statistics had a hiccup then. You could add another trace with the same entity but no statistics. You could also make a custom fn filter that only shows it if the statistics are missing. If you are not a programmer it will be a bit of a project in itself

**Comment by tomatensaus** [comment] 2023-05-03 05:35
Long term statistics consistently have hiccups, from the graph below the data for 2May also shows zero today (Yesterdaty it was displaying the correct values). At the end of each day the daily values in statistics are set to zero. Compare with the graphs from yesterday where 2 May had values. 

![image](https://user-images.githubusercontent.com/1019233/235838807-20829f99-7141-467c-b49b-8823dd1c9e3d.png)

**Comment by dbuezas** [comment] 2023-05-03 06:34
You may want to add an issue in HA core for this. It looks like an issue in the long term statistics component

**Comment by tomatensaus** [comment] 2023-05-03 07:37
I logged this bug, hopefully it will make sense [https://github.com/home-assistant/core/issues/92391](https://github.com/home-assistant/core/issues/92391)

**Comment by tomatensaus** [comment] 2023-05-05 11:37
I did notice that selecting "change" as the statistic option shows the correct value on my graph in the standard components. Screenshot below
![image](https://user-images.githubusercontent.com/1019233/236446843-26f4d492-5207-41c9-aefd-abcd3d9ad3c6.png)

I looked through https://github.com/dbuezas/lovelace-plotly-graph-card/blob/master/src/recorder-types.ts and could not find any equivalent definition. Is it not implemented? Is it new? or did I perhaps miss it?

At this stage I am thinking that using "statistic: state" does not work as my last_reset is not populated on the entity, and it is a daily total so being reset each day which might cause the statistics to record the daily movement from 0 to 0.

**Comment by dbuezas** [comment] 2023-05-05 17:32
That must be new. Could you try adding an "fn" filter and see if "change" is inside the statistics parameter?

**Comment by tomatensaus** [comment] 2023-05-06 13:52
> statistics

![image](https://user-images.githubusercontent.com/1019233/236628268-5db2abd7-fde2-4f2a-affd-4dac2d5c8457.png)

I think I figured out how to log the statistics object, and no I do not see the "Change" as one of the returned values above.

**Comment by dbuezas** [comment] 2023-05-06 13:55
That looks correct. I don't know what this "changed" statistic is.

**Comment by dbuezas** [comment] 2023-05-06 13:57
We're passing the data that HA sends back unmodified to that object: https://github.com/dbuezas/lovelace-plotly-graph-card/blob/master/src/cache/fetch-statistics.ts#L29

**Comment by tomatensaus** [comment] 2023-05-06 14:24
I see it is listed in the HA source code

https://github.com/home-assistant/frontend/blob/dev/src/data/recorder.ts

**Comment by dbuezas** [comment] 2023-05-23 18:06
High five people!
https://github.com/home-assistant/core/pull/92848/files#diff-39951366dd56691c4e51988078d3295e0ba6fc8a6089f719ac4f054886435608R1659

The wizzard emontnemery from the Home Assistant team made the HA api align data to multiples of periods, I'll close this issue and the fix will land in the next monthly HA.

**Closed by dbuezas** 2023-05-23 18:06 UTC
Labels: bug
