### ISSUE TITLE
Length of the plotly card is no longer adjustable since 2022.11.x

### ISSUE THREAD

**Issue by oneteam2win** [dbuezas/lovelace-plotly-graph-card#157] opened 2022-11-23 22:07 UTC
First of all, many thanks for the effort in developing and designing the card.

Now my challenge.
Since the update to 2022.11.4 the plotly cards are shortened.
No matter what I specify as the width, the card length is only as long as the title of the card.
![image](https://user-images.githubusercontent.com/57256232/203653853-355ff54b-8fe5-46d3-9a87-e6c98160ebec.png)

Previously I could position the plotly windows exactly in the picture-elements card by specifying the position, height and length.
Now the windows are aligned centrally and as already mentioned the length of the window corresponds to the length of the title.
Enclosed my config:

  - type: custom:plotly-graph
    entities:
      - entity: switch.poolpumpe::current_consumption
        line:
          fill: tozeroy
    hours_to_show: 12
    refresh_interval: 10
    title: Pool pump
    layout:
      xaxis:
        rangeselector:
          'y': 1.2
          buttons:
            - count: 12
              step: hour
            - count: 1
              step: day
      height: 180
      width: 400
    config:
      scrollZoom: false
    style:
      top: 52%
      left: 50%
  - type: custom:plotly-graph
    entities:
      - entity: sensor.full_flush_switch_measuring_power
        line:
          fill: tozeroy
    hours_to_show: 12
    refresh_interval: 10
    title: Irrigation pump consumption
    layout:
      xaxis:
        rangeselector:
          'y': 1.2
          buttons:
            - count: 12
              step: hour
            - count: 1
              step: day
      height: 180
      width: 400
    config:
      scrollZoom: false
    style:
      top: 72%
      left: 50%

**Comment by oneteam2win** [comment] 2022-11-25 22:01
I have now found out that it has nothing to do with the HA version used.
I have now installed plotly version 1.4.7 on a trial basis and the values for height and width are displayed correctly again.
![image](https://user-images.githubusercontent.com/57256232/204058814-b5d4128c-a080-4976-90b4-c1095aef00c6.png)

**Comment by dbuezas** [comment] 2022-12-20 14:45
This seems to be only affecting you. Please format the yaml using these triple backquotes so it is readable
` ```yaml `
`your yaml here`
` ``` `

**Comment by dbuezas** [comment] 2022-12-21 08:38
Closing as I can't reproduce it. Feel free to reopen if this stills occurs to you.

**Closed by dbuezas** 2022-12-21 08:38 UTC
