### ISSUE TITLE
Some findings with the new 2.0.1-Beta release

### ISSUE THREAD

**Issue by netweaver1970** [dbuezas/lovelace-plotly-graph-card#169] opened 2023-01-03 16:28 UTC
Hi, 
I have a few findings with the new 2.0.1-beta version: a problem in the handling of Lambda’s (maybe something about different handling of missing datapoints?), a difference in Spline type display and (potential) memory issues/crashing/loss of functionality?

Example for the first 2 finding: (always same dataset)
1st finding, look at the 3rd graph, the Abs. Hum. calculation. Fully calculated in Lambdas on the basis of the 2 graphs above.
2nd finding, not really an issue, I like the visuals more in the newer version. But I mention it anyway, as I feel there’s a significant difference.

2.0.1Beta
![image](https://user-images.githubusercontent.com/18028618/210398268-ef35f73e-8f20-4d4e-bed5-6a9554ed4c0f.png)

1.8.4
 
![image](https://user-images.githubusercontent.com/18028618/210398295-57acff9d-618f-4fe8-815a-d797cd888a09.png)

3rd finding, when increasing the time window to 14 days (or longer), the graph never ‘comes back’ complete. The image is frozen and the grouping period ‘at the bottom’ is never updated.
![image](https://user-images.githubusercontent.com/18028618/210398322-a4b9c2a8-2091-40a9-ad81-65745a2a6b2c.png)
 

This is my current YAML: https://pastebin.com/9HBZQmKm
Only thing I could find in the DevTools was this :
![image](https://user-images.githubusercontent.com/18028618/210398435-150cc43e-cede-4ee9-b509-5a0e66fecc94.png)

Thanks for the continued support and improvements. If all is stable I'll migrate my lambda to filters as well. Or earlier if really needed.

Cheers,

**Comment by dbuezas** [comment] 2023-01-03 17:12
Thanks for the report!
Can you come up with a minimum way of reproducing this?
The yaml and screenshots are way too big for me to try to debug this. Thanks!

**Comment by netweaver1970** [comment] 2023-01-03 19:32
ok, new try. All charts cut down to only 1 room/trace. Of course, showing the same behaviour:

It really looks (my guess) like the handling of non-existing values is different in both versions, and that screws up the (calculated) 3rd chart. 

24hr window: (the gap today around 15:00 is due to HA reboot, to install latest patch release). You can see a patchy 3rd chart but there is still something calculated for today.
![image](https://user-images.githubusercontent.com/18028618/210423843-e025ceac-9cbd-4165-917a-dea39c7aa623.png)

72hr window : nothing visible any more in the calculated Abs Hum. chart for today...
![image](https://user-images.githubusercontent.com/18028618/210424256-6cd38817-10fc-447e-9478-d564e2f0fbd0.png)

Also, in this beta, it seems no data is retrieved at all before a certain time on Dec 24th, independent of how I go to the data, either via manually selecting a bigger time window or simply scrolling back in time (as I did for the below screenshot):
![image](https://user-images.githubusercontent.com/18028618/210424793-708e458e-9ed6-4bb6-a6b3-49d4e3c3d01d.png)

Also, I never get to see the period grouping at the complete bottom of the charts any more. So I think the auto grouping is also not working.

This is my cut-down YAML, only 3 traces left, each on 1 chart + some formatting to get it into 3 separate charts. But even when I all combine all 3 traces it into 1 chart, then I get the same issues.

`type: custom:plotly-graph
entities:
  - entity: sensor.th_guest_temperature
    statistic: mean
    legendgroup: 6
    name: Guest
    yaxes: y1
    line:
      dash: dot
      shape: spline
      color: red
    lambda: |-
      (ys ,xs) => {
        window.temperature_guest = {xs,ys};
        return ys;
      }
  - entity: sensor.th_guest_humidity
    statistic: mean
    legendgroup: 6
    showlegend: false
    name: Guest
    yaxes: y2
    line:
      dash: dot
      shape: spline
      color: red
  - entity: sensor.th_guest_humidity
    showlegend: false
    statistic: mean
    legendgroup: 6
    name: Guestroom AH
    unit_of_measurement: g/m³
    lambda: |-
      (ys, xs) => {
        const t = window.temperature_guest;
        const h = {xs, ys:ys.map(parseFloat)};
        return h.ys.map((rh, i) => {
          const T = parseFloat(t.ys[i-1]);
          return (6.112 * Math.exp((17.67 * T)/(T+243.5)) * rh * 2.1674)/(273.15+T);
        }) 
      }
    yaxes: y3
    line:
      color: red
      shape: spline
      dash: dot
hours_to_show: 24
no_default_layout: true
layout:
  dragmode: pan
  margin:
    t: 30
    l: 50
    r: 30
    b: 50
  showlegend: true
  height: 950
  legend:
    x: 0
    'y': 1
    bgcolor: rgba(0,0,0,.4)
    orientation: h
    itemsizing: fixed
    font:
      size: 10
  grid:
    rows: 3
    columns: 1
    roworder: top to bottom
  yaxis:
    title:
      text: Temperature
  yaxis2:
    title:
      text: Humidity
  yaxis3:
    title:
      text: Abs. Humidity
  plot_bgcolor: black
  y1:
    gridcolor: whitesmoke
    zeroline: false
    fixedrange: true
  xaxis:
    rangeselector:
      'y': 1.02
      buttons:
        - count: 3
          step: day
        - count: 7
          step: day
        - count: 14
          step: day
        - count: 1
          step: month
        - count: 3
          step: month
        - count: 12
          step: month
        - count: 36
          step: month
defaults:
  entity:
    line: null
    period:
      24h: 5minute
      3d: 5minute
      7d: hour
      14d: hour
      1M: day
      3M: day
      12M: week
      36M: month
  width: 1
title: Climate
`

**Comment by dbuezas** [comment] 2023-01-03 20:03
Ok, that's a bit easier to digest.
Interesting. It looks like the fetching of statistics is behaving weird. That's untouched, so I don't understand why they would be different between both versions.

Regarding the periods, what you setup as auto-period is just on the edge of your defined ranges. This may make it fall sometimes below and some time above the threshold. Just to be sure, please try this:
```yaml
period:
      0s: 5minute
      6d: hour
      29d: day
      11M: week
      35M: month
```

As to why the period is not shown anymore, I'll take a look

**Comment by dbuezas** [comment] 2023-01-03 20:14
And you were right, auto period was broken. Give beta 2.0.2 a try

**Comment by netweaver1970** [comment] 2023-01-03 20:35
Hurray, seems it works 100% now, with 2.0.2-beta. No changes were needed. I'll keep an eye on all new versions too. Thanks again!

**Comment by dbuezas** [comment] 2023-01-03 20:42
Yey! Good to hear! Thanks for testing and reporting!

**Comment by dbuezas** [comment] 2023-01-04 14:38
Closing now as solved. Try the filters, they feel so much natural than lambdas to me!

**Closed by dbuezas** 2023-01-04 14:38 UTC
Labels: bug
