### ISSUE TITLE
But in HomeAssistant statistics API

### ISSUE THREAD

**Issue by andrekuehne** [dbuezas/lovelace-plotly-graph-card#180] opened 2023-01-09 13:29 UTC
**Describe the bug**
When scrolling in time and using a derivative filter, the currently displayed first (oldest) datapoints appear to jump around (change their y-value). Similarly, clicking "Autoscale" triggers the same behavior, with values jumping around & additionally the x-axis expanding with each click.

**Screenshots**
A video of this effect in action is shown here:
[https://photos.app.goo.gl/bb7JfDMtFLbSyMm68](url)
![screen-20230109-135305_2](https://user-images.githubusercontent.com/777196/211360707-57520be8-bc16-484d-9d49-ff0c3a9845c9.gif)

**YAML**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.temp_out_c308_temperature
    statistic: mean
    type: bar
    period: day
    filters:
      - derivate: d
hours_to_show: 240
refresh_interval: 10
title: Derivate test
```

**Comment by dbuezas** [comment] 2023-01-09 16:44
Interesting, I'll investigate.

**Comment by dbuezas** [comment] 2023-01-10 22:07
Can you remove the derivative filter and do the same scrolling? I don't see anything wrong in the filter code so I'm starting two question the way I am stitching different data fetches (or what HA returns)

**Comment by andrekuehne** [comment] 2023-01-10 22:14
Hah, same problem without the derivative (both for scrolling and autoscale clicking). So it's not the derivative. Great catch!

**Comment by dbuezas** [comment] 2023-01-10 22:34
Oh wow!
You found a bug in home assistant.
The server is responding different things about the same day.
These are two consecutive answers from the server from a scroll. Same timestamps, different statistics
```json
{
    "start": 1673218800000,
    "end": 1673305200000,
    "mean": 5.312334714347086,
    "min": 5.22,
    "max": 5.45,
    "last_reset": null,
    "state": null,
    "sum": null
}
```
```json
{
    "start": 1673218800000,
    "end": 1673305200000,
    "mean": 5.406622571415406,
    "min": 5.38,
    "max": 5.44,
    "last_reset": null,
    "state": null,
    "sum": null
}
```

---

To see it more clearly, here each of the values of each datapoint put together
```json
    "end": 1673305200000,
    "end": 1673305200000,
    "last_reset": null,
    "last_reset": null,
    "max": 5.44,
    "max": 5.45,
    "mean": 5.312334714347086,
    "mean": 5.406622571415406,
    "min": 5.22,
    "min": 5.38,
    "start": 1673218800000,
    "start": 1673218800000,
    "state": null,
    "state": null,
    "sum": null
    "sum": null
```   

Same timestamps, different min, mean and max.

Would you report this here?
https://github.com/home-assistant/core/issues

**Comment by dbuezas** [comment] 2023-01-10 22:43
Here's the report material. Link it to this issue please so I can track it too :) (just paste this link in the report: https://github.com/dbuezas/lovelace-plotly-graph-card/issues/180#issuecomment-1377983703)

# Bug in statistics API?

Requesting different but overlapping intervals returns different data.
See the first element of the first request and the second element of the second request.

# Request 1

```js
hass.callWS({
    "type": "recorder/statistics_during_period",
    "start_time": "2023-01-09T22:36:29.577Z",
    "end_time": "2023-01-10T22:36:29.578Z",
    "statistic_ids": [
        "sensor.teich_temperature"
    ],
    "period": "day"
})
output = [
    {
        "start": 1673218800000, // SEE THESE START/END TIMESTAMPS
        "end": 1673305200000,   
        "mean": 5.24426256625,
        "min": 5.22,
        "max": 5.26,
        "last_reset": null,
        "state": null,
        "sum": null
    },
    {
        "start": 1673305200000,
        "end": 1673391600000,
        "mean": 5.211063944814258,
        "min": 5.12,
        "max": 5.27,
        "last_reset": null,
        "state": null,
        "sum": null
    }
]
```
---
# Request 2

```js
hass.callWS({
    "type": "recorder/statistics_during_period",
    "start_time": "2023-01-08T14:57:49.597Z",
    "end_time": "2023-01-09T14:57:49.598Z",
    "statistic_ids": [
        "sensor.teich_temperature"
    ],
    "period": "day"
})
output = [
    {
        "start": 1673132400000,
        "end": 1673218800000,
        "mean": 5.399998164044445,
        "min": 5.33,
        "max": 5.45,
        "last_reset": null,
        "state": null,
        "sum": null
    },
    {
        "start": 1673218800000,  // THE SAME AS THESE ONES
        "end": 1673305200000,
        "mean": 5.343677672407825, // BUT DIFFERENT VALUES
        "min": 5.23,
        "max": 5.45,
        "last_reset": null,
        "state": null,
        "sum": null
    }
]
```

**Comment by dbuezas** [comment] 2023-01-10 22:45
Closing as this is not a bug in this card. Thank you @andrekuehne !

**Closed by dbuezas** 2023-01-10 22:45 UTC

**Comment by dbuezas** [comment] 2023-05-04 17:26
One of the engineers from the Home Assistant team has reached out and it looks like we were right. We may get a fix for this soon 🤞

**Comment by andrekuehne** [comment] 2023-05-04 17:43
Excellent! Thanks for following up, I saw his message but didn't have the time to contact him.

**Comment by andrekuehne** [comment] 2023-10-21 08:12
From my checking Github on the HA issue it appears the change that was supposed to fix this was merged, however the behavior in the plots is not fixed as of now (looking at my heating efficiency graohs again since it's getting cold 😅) - any idea why?

**Comment by dbuezas** [comment] 2023-10-21 11:20
No idea why, I am very short on time at the moment, can you reproduce the HA issue with the experiment from above?
