### ISSUE TITLE
Feature request: add offset field

### ISSUE THREAD

**Issue by zanna-37** [dbuezas/lovelace-plotly-graph-card#33] opened 2022-03-17 20:48 UTC
https://github.com/RomRider/apexcharts-card has a `offset` field that is used to "move" the x values of a series.
I already tried to use data transformation, but the problem is that values outside the graph are not available.

_Why is it a problem?_ I have an entity that gives a forecast of a value 12h in the future. I therefore need to move the entity values 12h in the future because the current value refers to a future event. However, I can only "move" data that are already visible, which leaves a blank space. If I scroll left, the data is loaded, but it is of course inconvenient.

![immagine](https://user-images.githubusercontent.com/43404980/158891776-29e3255b-b13f-46d7-8d6e-d8d911b22767.png)

-----
The transformation I used:
```yaml
# this works only partially
    lambda: |-
      (ys, xs) => {
        const result = {x:[], y:[]}
        for (let i = 0; i < xs.length; i++) {
          const x = xs[i].setHours(xs[i].getHours()+12) # move the x-values (<--)
          const y = ys[i]
          if (x<((new Date).setHours((new Date).getHours()+2))){ # only show 2 hours in the furure (not relevant for this issue)
            result.y.push(y)
            result.x.push(x)
          }
        }
        return result;
      }
```

**Comment by zanna-37** [comment] 2022-10-26 07:48
Is there anything that can be done?

**Comment by dbuezas** [comment] 2022-10-26 07:53
Hi zanna,
Please send me how the apex yaml with offset looks like an I'll add the feature

**Comment by zanna-37** [comment] 2022-10-26 08:28
There are 3 relevant rows.

```yaml
type: custom:apexcharts-card
graph_span: 12h
span:
  offset: +2h  # <------------------- HERE and...
               # This indicates how much of the future the graph should show in the initial view
series:
  # This serie outputs the forecasted power production in 12 hours from now
  - entity: sensor.power_forecast_production_in_12hours
    group_by:
      func: raw
    offset: '-12h'  # <------------------- ...HERE and...
                    # This shifts the serie
    extend_to: false
    float_precision: 0
    color: '#AAAAAA'
    stroke_width: 1
    show:
      hidden_by_default: false
    yaxis_id: watt
  # This serie outputs the forecasted power production for the next hour
  - entity: sensor.power_forecast_production_next_hour
    group_by:
      func: raw
    offset: '-1h'  # <------------------- ...HERE
                    # This shifts the serie
    extend_to: false
    float_precision: 0
    color: '#333333'
    stroke_width: 1
    show:
      hidden_by_default: false
    yaxis_id: watt
yaxis:
  - id: watt
    decimals: 0
    apex_config:
      forceNiceScale: true
```

_Side note: I argue that the '-1h' should instead be '+1h'. Because it is shifting a value that happens now, to the future. The way apex implemented it is confusing but that's a minor detail._

**Comment by zanna-37** [comment] 2022-10-28 08:26
If you need more assistance or if you want me to describe the feature better, just ask.
Thank you!

**Comment by dbuezas** [comment] 2022-10-28 08:44
Thanks, I haven't sat down on this yet. I think it will be fairly to implement.
I'm not sure I understand what the span: offset: 2h does. Can you expand on that?

**Comment by zanna-37** [comment] 2022-10-28 09:13
It basically tells how much "future" we see by default. (See the purple annotation)

![image](https://user-images.githubusercontent.com/43404980/198550045-9579bbb7-d72a-4b62-a67d-329315e57c43.png)

-----
More context:
_The real grey line (before applying the +12h offset) would have been much more on the left. What you see here is the one that has been shifted in the future by 12h._

**Comment by dbuezas** [comment] 2022-10-28 09:59
Oh, I see.
Let's review the algorithm I have in mind:
* Get the range visible in the screen
* Expand its upper limit it by `span:offset:` 
* Shift the range by the entity' offset offset to
* Fetch that offset range
* Subtract the entity offset back from each data point returned by HA

Did I get it right?

**Comment by zanna-37** [comment] 2022-10-28 10:30
Let's assume that:
- Now is `12:30`
- Entity offset is 3h
  - → _Means that a data point generated now will be plotted 3h in the future_
- `hours_to_show: 2`
  - Visible range is initially `10:30 - 12:30`
- `span:offset:` is `1h`


Then:
* Get the range visible on the screen
  - → _`10:30 - 12:30`_
* Shift the visible range by `span:offset:`
  - → _Visible range is now `11:30 - 13:30`_
* Shift the range by `(-1) * (entity's offset)`
  - → _Shift entity range by `-3h`. So entity range to fetch is `8:30 - 10:30`_
* Fetch the resulting range
  - → _fetch `8:30 - 10:30`_
* Add the entity offset back from each data point returned by HA
  - → _Shift entity range by `+3h`. So entity range to display is `11:30 - 13:30` (Which, of course, matches the visible range)_
* Plot

**Comment by dbuezas** [comment] 2022-10-28 11:15
And that's what you expect, right?

**Comment by zanna-37** [comment] 2022-10-28 11:37
Yes, I just augmented your algorithm with an example, so there is less ambiguity.

**Comment by dbuezas** [comment] 2022-10-28 12:39
Perfect, i may try it today

**Comment by dbuezas** [comment] 2022-10-30 20:06
I just gave it a try and it seems to try. I'll try to make a veta release tomorrow and I'd really appreciate it if you tested it a bit more (I don't know the use case that well) :)

Also, do you want to write down the lines for the readme later? It can be done in github's UI

**Comment by zanna-37** [comment] 2022-10-30 21:35
Sure, of course. =)

**Comment by dbuezas** [comment] 2022-10-31 16:29
This got really tricky, there is some bug in plotly (maybe) that makes this feature jump like crazy. I think it is because there is data out of the visible range right from the start.

Anyway, I think I found how to fix that, and it will make the non-offsetted plots less buggy too!

I'll push a beta version for you to try and give feedback on, I'd appreciate it if you tell me any bugs you find and also PR the instructions (maybe with some pics? :) ).

If everything goes well this is almost done, just needs some cleanup.

**Comment by dbuezas** [comment] 2022-10-31 17:02
https://github.com/dbuezas/lovelace-plotly-graph-card/releases/tag/v1.6.0-alpha
This feature owes me 5 hours of my life

**Comment by zanna-37** [comment] 2022-11-01 10:04
Amazing! Thank you very much!
If you ever need something on [my repo](https://github.com/zanna-37/hass-swipe-navigation) you'll have priority support. 😉
By the way, I think we are getting there but there are still issues.

When I click the drag button this message is shown: _"Error computing range subtraction. Please report an issue in the repo of this card and share this:[null,null][949522275000,981144675000]"_

By the way, I think you'd better remove the release until we fix everything. I'll have a look into it myself.

**Comment by zanna-37** [comment] 2022-11-01 13:40
Ok, I'm working on it and I'll post a pull request once I finish.

One question though, why did you decide to remove this piece of code https://github.com/dbuezas/lovelace-plotly-graph-card/commit/cc7aed03f101ccd13dbc8ed84a0bc1391b422bf4#diff-f0b1423191726c0f2981ced42942c5c7743094bb86c9c05495ca9fa00a855583L43-L63?

**Comment by dbuezas** [comment] 2022-11-01 13:56
Oh, that's awesome that you'll make a PR!
I have an unpushed commit with a bunch of fixes, lemme push that it first (will save you some headaches)

The removal of that code was because it was getting in my way, I'll put it back

**Comment by dbuezas** [comment] 2022-11-01 13:58
There is one bug in ploty which is making me crazy: if there are discontinuities in the plot (unavailable, which is transformed to null to let plotly know to leave a gap), there are a lot of artifacts when scrolling

**Comment by dbuezas** [comment] 2022-11-01 13:58
Ill push in an hour (not at my computer now)

**Comment by dbuezas** [comment] 2022-11-01 14:00
The removed piece of code may the culprit of this : https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/92#discussioncomment-4026237

**Comment by dbuezas** [comment] 2022-11-01 14:00
And your component looks super useful! I'll definitely give it a try :)

**Comment by zanna-37** [comment] 2022-11-01 14:06
In the removed piece of code, can you reword the [documentation](https://github.com/dbuezas/lovelace-plotly-graph-card/commit/cc7aed03f101ccd13dbc8ed84a0bc1391b422bf4#diff-f0b1423191726c0f2981ced42942c5c7743094bb86c9c05495ca9fa00a855583L44-L50) that you wrote so it is clearer? Maybe with some examples.
I would like to fix that as well, but I need to deeply understand it first.

**Comment by dbuezas** [comment] 2022-11-01 14:30
Ok, I hadn't changed that much, just a fix for the NaN in ranges.
The branch is now up to date, go for it! :) 

Regarding the removed piece of code, it may stay gone because of this:

> The removed piece of code may the culprit of this : https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/92#discussioncomment-4026237
> 
> That piece of code was mostly there to force points in the presebt, and have the visible range be correct by letting plotly autoscale the xaxis.
> With the offset feature, this trick is no longer viable so I implemented it the right way. But now I have this ghost traces.
> You'll see in the upcoming commit

**Comment by dbuezas** [comment] 2022-11-01 14:31
Regarding the docs, it was too long ago... I'm not sure anymore :(

**Comment by dbuezas** [comment] 2022-11-01 16:05
I manage to reproduce the misplotting I got, and find the plotly bug:
```yaml
type: custom:plotly-graph-dev
entities:
  - entity: sensor.nothin
    lambda: |-
      () => ({
        x:[-60,-50,-40   ,-30     ,-20 ,-10, 0].map(x => new Date(Date.now()+x*1000*60)),
        y:[0. ,1. ,null ,3       ,null,4,5],
      })
hours_to_show: 1
```
it happens in the weird case where there is a single value sandwiched by 2 nulls. In this case, plotly seems to lose track of its traces (I hypothesise this is because the single number is not a line, so some for loop probably stops early).

The offset feature forced me to implement correctly some hacks that did bother me, and produced some odd jumps here and there. Interestingly (and annoyingly) they also hid this plotly bug.

**Comment by zanna-37** [comment] 2022-11-01 16:40
Ok, so what do you propose?

**Comment by dbuezas** [comment] 2022-11-01 16:52
Did you fix the bug you found?
Or did my push fix it?
I'll fix this small bug i found, but the rest is more or less final. 
You can already make a pr with that branch with the readme docs :) you have some real use case and understanding. Btw, are the signs of the offset intuitive to you like they are?

**Comment by dbuezas** [comment] 2022-11-01 16:56
> Ok, so what do you propose?

I guess you are asking what my proposed solution is. I was thinking about duplicating any lonely data point that finds itself between unavailables. That should give plotly some rest.
I also need to confirm the deleted block you mentioned really isn't needed.

**Comment by zanna-37** [comment] 2022-11-01 18:57
The deleted block is needed to delete the fictitious data points that HA make up. I'm working on it.

> I was thinking about duplicating any lonely data point that finds itself between unavailables. That should give plotly some rest.

About this, I do not experience the problem that you are pointing out. I think it should live in a separated issue.

**Comment by dbuezas** [comment] 2022-11-01 19:17
> I think it should live in a separated issue.

You can reproduce it with the lambda. It's true that it sounds unrelated to the offsets, but the old code hid this effect (i assume because the range of the xaxis was never set explicitly)

**Comment by dbuezas** [comment] 2022-11-01 19:18
Did you fix the bug you found before?

**Comment by zanna-37** [comment] 2022-11-01 19:26
> Did you fix the bug you found before?

Nope, the problem is caused by the fictitious data points that HA adds. I need I way to detect them and I'm working on that. Once it's fixed I think this issue is solved.

**Comment by zanna-37** [comment] 2022-11-01 19:28
> Did you fix the bug you found before?

Nope, the problem is caused by the fictitious data points that HA adds. I need I way to detect them and I'm working on that. Once it's fixed I think this issue is solved.

> You can reproduce it with the lambda. It's true that it sounds unrelated to the offsets, but the old code hid this effect (i assume because the range of the xaxis was never set explicitly)

Now I see. Anyway let's make a separate issue. Before merging everything on master we solve both of them.

**Comment by dbuezas** [comment] 2022-11-01 20:59
Ghosting on lonely datapoints sandwiched between unavailable is fixed in the [this](https://github.com/dbuezas/lovelace-plotly-graph-card/commit/b784324bbe3cb0cfb2f3c0d25fbd3a088e63137a) commit to the offsets branch.

**Comment by zanna-37** [comment] 2022-11-01 21:29
> Ghosting on lonely datapoints sandwiched between unavailable is fixed in ~[this](https://github.com/dbuezas/lovelace-plotly-graph-card/commit/b784324bbe3cb0cfb2f3c0d25fbd3a088e63137a) commit to the offsets branch~.
> 
> Update: I don't know how I got confused, but the but the bug is in master too, so this is (as you said) totally unrelated to this issue

Oh ok, wouldn't it be appropriate to open a issue on plotly?

> Idea: They may have exact same timestamp as the end date of the fetched data. In that case, one option may be to always fetch up to end timestamp + 1 and then always remove the last one

This might work however:
- a data point might coincide with the range boundary
  - in this case we shouldn't remove it
- we only have to remove the point when it is not an edge point (not first nor last of fetched points)

**Comment by dbuezas** [comment] 2022-11-01 21:53
> a data point might coincide with the range boundary

Yes, but we can fetch up to end+1. If a data point coincides, we didn't want it anyway.

**Comment by zanna-37** [comment] 2022-11-01 23:36
I'm close to a working solution, but I have work next days, so I'll do the best I can. Don't worry, I'll keep you posted. 😉 

In the meantime, since the branch has gone a little crazy with all the commits, do you mind if I rewrite the commit history (squashing and moving commits) so it's clearer?
I'll do the history-rewrite in my fork, and I'll then create the pull request.
If you are against it, and prefer to leave the commits as is, just tell me.

**Comment by dbuezas** [comment] 2022-11-02 09:17
As long as it doesn't change the line authors, I'm fine with that :).
In any case I'll squash and merge the pr branch to master in the end, so it shouldn't make a diff
I have to start working myself in the next couple of days, and I really want to merge the other autorange changes to master before that (master is a bit bugy at the moment).

**Comment by zanna-37** [comment] 2022-11-02 09:43
Ok, can you give me a deadline? If we can't make it, we should just extract (_read cherrypick_) the autorange changes from the branch and apply them on master.

**Comment by dbuezas** [comment] 2022-11-02 11:29
Tomorrow night? :) Then I can do it on Friday
Btw: #104 this may mean that the old fix is doing more harm than good

**Comment by zanna-37** [comment] 2022-11-02 12:00
By "old fix" you mean the removed code right?

**Comment by dbuezas** [comment] 2022-11-02 12:54
> By "old fix" you mean the removed code right?

Yes

**Comment by dbuezas** [comment] 2022-11-02 14:59
And for reference, #105 is one of the fixes in this branch. I thought it was specific to the offsets branch, but it isn't.

**Comment by zanna-37** [comment] 2022-11-02 23:27
For the sake of having things compartmentalized, I suggest leaving this issue just for the offset. I'll take care of implementing it myself based on what you already did.

Everything else (that lives on the offset-branch) should be cherry-picked and pushed to master separately.
In this way, you can push the important fixes fast, and I have the time to review the rest.

-----

To sum up:
- offset-raleted code → leave it to me
- the famous "removed code"
  - can be divided in 2: remove fictitious points and extend data to Date.now()
    - remove fictitious points → leave it to me, I'll open a separate pull request
    - extend data to Date.now() → let's save that for the future because it needs to be fixed, but it's not trivial
- everything else → you can cherry-pick it, or create new commits but they should be pushed to master separately from this issue

-----

A note on the "removed code".
I don't know if it is better to temporarily remove it from master until I fix it, or leave it there. Your choice.

**Comment by dbuezas** [comment] 2022-11-03 06:36
The risk if I sit down and cherry pick, rebase, etc, is that I may end up also accidentally fixing the "removed code" part :)

Afaik, the offset code already works fine, it is only the removal of duplicate points that I ignored.
Extending to Date.now is not needed anymore now that the range is set explicitly to match hours_to_show

**Comment by zanna-37** [comment] 2022-11-03 07:59
> Extending to Date.now is not needed anymore now that the range is set explicitly to match hours_to_show

Mmm, I don't agree, and I'll show you and example as soon as I can, but we can ignore it for now.

**Comment by dbuezas** [comment] 2022-11-07 07:36
FTR, extend to now is back. Although not strictly required for showing the right xaxis range anymore, It didn't feel right without (as you noted)

**Comment by dbuezas** [comment] 2022-11-07 20:24
@zanna-37 I think we are good to go now :) 
The ghosting bug you found persisted should be fixed now. It occurred when the "lonely" datapoint was right at the beginning/end of the series. e.g:
`[5, null, ...]`

5 is not sandwiched in nulls, but still feels lonely 😁 
Fixed [here](https://github.com/dbuezas/lovelace-plotly-graph-card/commit/799d4a86ddd1862a1fb1ea067090b514151df723)
<img width="744" alt="image" src="https://user-images.githubusercontent.com/777196/200407945-e87be388-d253-4a1b-b6ce-1c1dd905dc6b.png">

**Comment by zanna-37** [comment] 2022-11-07 20:33
> 5 is not sandwiched in nulls, but still feels lonely 😁

LOL 😂 poor point 😂😂😂.

**Comment by zanna-37** [comment] 2022-11-07 20:45
> @zanna-37 I think we are good to go now :)

I'll test it and add pics and docs to the README.
Give me some days, however, I'm a bit busy these days.

**Comment by dbuezas** [comment] 2022-11-07 21:09
Alright, I'll keep it rebased

**Comment by dbuezas** [comment] 2022-11-15 21:31
8 months after the request, the feature is released!
Thanks @zanna-37 for your contributions & discussions, it was a fun feature to work on!

**Closed by dbuezas** 2022-11-15 21:31 UTC
Labels: enhancement

**Comment by dbuezas** [comment] 2022-12-19 09:31
Comparison of downloads of latest vs previous version. I released on pretty much at the same hour and weekday (not on purpose) so it's shouldn't be a surprise that they are similar, but it still blows my mind that they are almost equal!

Interestingly, the Worldcup final didn't slow it down much hehe
![Screenshot_20221219-102733](https://user-images.githubusercontent.com/777196/208393064-cfce4d5f-3bac-4238-ad7f-bcbcbf9ac677.png)

**Comment by zanna-37** [comment] 2022-12-19 09:35
That's amazing 😂😂

**Comment by dbuezas** [comment] 2022-12-20 18:58
It's quite fascinating how closely it still follows the previous curve. 
<img width="902" alt="image" src="https://user-images.githubusercontent.com/777196/208744722-0a11a2ba-486e-410c-9e82-d6df8b80e560.png">

**Comment by zanna-37** [comment] 2022-12-25 17:02
It's seem too good to be true. Must try with mine.

**Comment by dbuezas** [comment] 2023-01-03 09:44
Hey @zanna-37,
There is one thing that is bothering me about this feature: I think the global offset should not only "scroll" the viewport into the future, but the data out of that range should be capped. I find this cumbersome because it makes autoscaling (i.e double click in the screen or clicking the modbar button) zooms out a lot when the same entity is also shown without offset. This is because there is data going into the future already in the cache.
Do you have anything against me capping its range? to only offset units into the future?

**Comment by dbuezas** [comment] 2023-01-03 10:17
Like this: https://github.com/dbuezas/lovelace-plotly-graph-card/commit/2f45a1350ae2f62dd0524b42de9f36dd5d8fea2b

**Comment by dbuezas** [comment] 2023-01-03 10:41
This is mostly because if two traces use the same entity, they'll share the cache, irrespective of the fact that one is offset. The result is that the cache system already knows two ranges, and it gladly returns them for both traces. Maybe the correct way would be to make the offset part of the cache key, it would be slightly less data efficient, but it will be free of these issues. Thoughts?

**Comment by zanna-37** [comment] 2023-01-03 11:09
I don't think I fully understand the implications.
Does this mean that you can only "see" `x` amount of future, where `x` is the global offset?
So that the future data past that point can never be seen?

**Comment by dbuezas** [comment] 2023-01-03 11:16
Example:
```yaml
offset: 1h
entities:
  - entity: sensor.mysensor
  - entity: sensor.mysensor
    offset: 10h
hours_to_show: 1
```

the cache will fetch two ranges: [now-1h, now+1h] (for the fist trace) and [now -1h -10h, now +1h - 10h] for the second one.
Now both ranges are in the cache, so if one zoomes out, the second one will not end in now+1h, but in now+1+10 hours, because there is data for that. There will also be a gap, so the trace will have a long straight line. And if one now does autoranging, the card will zoom out 11 h.
Makes sense now?

**Comment by zanna-37** [comment] 2023-01-03 11:29
That's clear, but what would change after your proposed modifications?

**Comment by dbuezas** [comment] 2023-01-03 11:31
That the traces offset into the future won't load beyond the global offset. I think I'll work on the caching instead, so they are kept separate

**Comment by zanna-37** [comment] 2023-01-03 12:34
But in this case one cannot see future value past the global offset even when scrolling. Is that correct? If so, I don't think it's a good idea. I would prefer having the cache records for the same entity (one for each offset. In this case, 2 records: 1 with offset 0, the other with offset 10h)

-----

Talking about the design, a possible improvement would be keeping all the information about a trace on the trace itself. To be clearer, it should be the trace's responsibility to know what its range is, not the cache's. In this way, when pressing autorange, the trace knows what to do, regardless of the cache. Now we are also using the cache to remember the data margins.

This is my vision:

- **Global cache (has raw data)**
  - Data is fetched from the home assistant database
  - It's a dumb blind cache
  - It is a raw copy of what home assistant has in its database
  - Data is never offsetted even if the plot trace is
  - Stores only what was fetched from the database
  - When the same entity is repeated in the plot, all the instances pull the data from the same cache record (regardless of offsets, lambdas, etc.)
- **Trace cache (has transformed data)**
  - Data is fetched from the Global cache  
  - It's private and each trace has its own, even when referencing the same entity
  - It implicitly stores the limits of the trace
  - The data here are offsetted according to the config
  - The data here are cached in its transformed state (after all filters/lambdas are applied)
    - _In this way computation is only done once_

This approach uses more memory, but it has the advantage of separating duties and also caching the lambda calculations.

One can also argue that with this new design the "Global cache" is only marginally useful because it always uses memory while only improving performance when we have different traces (each with a unique offset/lambda/filter) that reference the same entity.

Removing the "Global cache" and only leaving the "Trace cache" uses more memory but decreases calculations. And in my experience, the user is more likely to have a lot of RAM than a good processor, especially on mobiles.

**Comment by dbuezas** [comment] 2023-01-03 13:13
Yeah, I had something similar in mind. The cache currently works like the global one you describe, but when a trace asks for data, it applies the offset and adds the xs and ys arrays.
One option is to keep track of which ranges (but not data) each unique trace asked for ( unique as with the same cache key, where the key includes entity name, statistics vs states vs attributes, and offsets). 
I'm not sure that it justifies the effort (and bug potential) though, the easy way out is just add the offset to the "global" cache entity key.
After all, I bet theres 10 plots in the world that have the same entities multiple times with different offsets :)

**Comment by zanna-37** [comment] 2023-01-03 13:55
You underestimate your users. 😉
BTW yes, I agree that it's a lot of effort. My opinion is that we should transition the Global cache to Trace cache. It certainly uses more memory but everything works and you can also cache lambda calculations.

So the final implementation should have Trace cache only, without the Global cache.

The minimal-effort-maximum-gain step is instead adding the offset as a key to the cache.

**Comment by dbuezas** [comment] 2023-01-03 14:15
What's the difference between a trace cache, and a global one that distinguishes those with different offsets?

**Comment by dbuezas** [comment] 2023-01-03 14:31
Oh darng it! adding the offset to the cache key works almost perfectly, except when data comes in directly from home assistant (an entity got a new state and those are pushed instead of fetched)

**Comment by zanna-37** [comment] 2023-01-03 14:43
> What's the difference between a trace cache, and a global one that distinguishes those with different offsets?


that Trace cache should caches the final result, after all lambdas, filters (and of course offset) are applied.

Right know the lambda functions must be reevaluated.

> Oh darng it! adding the offset to the cache key works almost perfectly, except when data comes in directly from home assistant (an entity got a new state and those are pushed instead of fetched)

It would be better to have a single point where the offset is applied. Can't you update the cache code so that when a new state is available it is pushed to the cache similarly to when we fetch from db?

**Comment by dbuezas** [comment] 2023-01-03 15:39
> after all lambdas

That, unfortunately, won't work. It breaks for example all filters that do accumulation (e.g integration). In practice, I have luckily never seen this be a performance issue (except on a buggy/really inefficient implementation)
It also creates all sorts of issue when writing the yaml, where the filters, offsets, etc, may change at any moment.

> It would be better to have a single point where the offset is applied. Can't you update the cache code so that when a new state is available it is pushed to the cache similarly to when we fetch from db?

This is exactly how it works :) 
The issue is that when a trace is offset and a new present state appears, that's way into the future (for the offset trace).

I made a dirty implementation of keeping track of which range was queried by each trace here: https://github.com/dbuezas/lovelace-plotly-graph-card/commit/62dfeb0c881516f9e11b4b9d090d5ec2d80a6edf

The problem is not THAT bad actually, but this implementation is quick and dirty so I won't take it yet. The idea is simple: the cache tracks raw data as before, but there is a second structure storing all the ranges that each unique trace "asked for". It seems to work fine, it just has some minor issues b/c I didn't finish it.

If you have the time and energy, your feedback and opinions are very welcome! :) I really appreciate that you take time to discuss this things with me!

**Comment by dbuezas** [comment] 2023-01-03 17:17
Thanks!

> The "Trace cache" stores the data after offset, filters, and lambda are applied.

I think you missed the message above the last one. This kind of cache cannot be reused in the general case (think doing the integral of power (e.g W) to obtain energy (e.g kWh), more in my previous msg)

**Comment by dbuezas** [comment] 2023-01-03 18:27
Ok, for now I decided to solve it in the simplest way possible:

The following exceptions apply to entities with offsets:
* They get their own cache, meaning that data will be fetched twice if the same entity is in the plot with a different (or no) offset.
* websocket state updates are not used to fill the cache (but a request to the server may be triggered)
* extend_to_present is ignored (because extending to an offset present may be further into the future and that makes a mess)

This fixes all visual glitches perfectly and the code changes are minimal and less prone to errors:
https://github.com/dbuezas/lovelace-plotly-graph-card/pull/164/commits/65439ed6f87687884f4c540d79f9579afcc374ec

**Comment by zanna-37** [comment] 2023-01-04 10:22
I indeed missed it, sorry for that.

> The issue is that when a trace is offset and a new present state appears, that's way into the future (for the offset trace).

I don't understand why this shouldn't work. If the new state is pushed to the cache, it is indistinguishable from being pulled from the db? Isn't it?

BTW if you want we can organize a call so we can meet and discuss better. Discord works for me, for example.

**Comment by zanna-37** [comment] 2023-01-04 10:48
> extend_to_present is ignored (because extending to an offset present may be further into the future and that makes a mess)

Not sure about that. I would keep it. But of course, `extend_to_present` should be applied before the offset.

**Comment by dbuezas** [comment] 2023-01-04 14:36
>  I don't understand why this shouldn't work. If the new state is pushed to the cache, it is indistinguishable from being pulled from the db? Isn't it?

Yes, but it will only be pulled from the db after a scroll that drives it into the visible range. If the offset pushes the trace into the future, then "now" could be "24 hours into the future", and if I add that datapoint, then autorange will zoom out to cover that point. For the user it makes no difference, it is just another slight inefficiency. I left a "TODO" there, I'll eventually get back to it, but it is not noticeable. This will be covered by keeping track separately of what ranges were requested by which traces, and filtering the cache with that before returning from the cache.

> Not sure about that. I would keep it. But of course, extend_to_present should be applied before the offset.

This produces the same issue: present + offset is far into the future, so autorange makes a mess

> BTW if you want we can organize a call so we can meet and discuss better. Discord works for me, for example.

Oh sure! let's do that! I'm dbuezas#1110 in the HA server
